/**
 * Book interface for library management system
 * All fields except id, _id, photo, and status are REQUIRED for book creation
 */
export interface Book {
  /** Auto-generated by backend (OPTIONAL for creation) */
  id?: number;
  /** MongoDB ObjectId (OPTIONAL for creation) */
  _id?: string;
  /** Book title (REQUIRED) */
  title: string;
  /** Book author (REQUIRED) */
  author: string;
  /** ISBN number (REQUIRED) */
  isbn: string;
  /** Publication year (REQUIRED) */
  publishedYear: number;
  /** Total number of copies (REQUIRED) */
  totalCopies: number;
  /** Currently available copies (REQUIRED) */
  availableCopies: number;
  /** Book cover image URL (OPTIONAL) */
  photo?: string;
  /** Book status - calculated by backend (OPTIONAL) */
  status?: string;
}
